# PINN_Framework/environment.yml
name: pinn-framework-env # 新的环境名称
channels:
  - pytorch # For PyTorch
  - conda-forge # For fastscape and others
  - defaults
dependencies:
  # 核心 Python 和 PyTorch
  - python=3.10 # 建议指定一个 Python 版本 (例如 3.10)
  - pip # 确保 pip 可用
  - pytorch # 让 Conda 处理 PyTorch 安装 (CPU/GPU)
  - cpuonly # 默认安装 CPU 版本的 PyTorch，如果需要 GPU 版本请修改或移除此行
  # - pytorch-cuda=11.8 # GPU 用户请取消注释并根据你的 CUDA 版本修改

  # 核心科学计算和数据处理
  - numpy # 数值计算基础库
  - scipy # 科学计算库，用于优化、插值等
  - pandas # 数据分析库

  # Fastscape 相关依赖
  - xarray # 用于处理带标签的多维数组
  - xsimlab # 用于构建模拟模型
  - fastscape # 地形演化模拟库，Conda 会处理其 Fortran 依赖

  # 可视化
  - matplotlib # 绘图库
  - pillow # 图像处理库

  # 工具和实用程序
  - pyyaml # YAML 文件解析
  - tqdm # 进度条
  - tensorboard # 训练可视化
  - omegaconf # 配置管理，支持变量插值
  - netcdf4 # 用于 NetCDF 文件处理 (Fastscape 可能输出)
  - scikit-image # 图像处理库，用于数据分析和可视化

  # Pip-installed dependencies (开发工具或 Conda 中不易获取的包)
  - pip:
    - pytest # 单元测试框架
    - pytest-mock # 用于测试中的模拟
    - pytest-cov # 测试覆盖率报告