# PINN_Framework/configs/train_config_4090.yaml
# 针对单卡4090优化的训练配置

# --- 通用设置 ---
output_dir: results/
run_name: pinn_train_4090_${now:%Y%m%d_%H%M%S}
seed: 42
run_options:
  device: cuda  # 强制使用GPU

# --- 数据设置 ---
data:
  processed_dir: data/processed
  train_split: 0.8
  val_split: 0.1
  num_workers: 8                # 充分利用CPU多核，提高数据加载效率
  normalization:
    enabled: true
    compute_stats: true
    stats_file: ${data.processed_dir}/norm_stats.json

# --- 模型设置 ---
model:
  output_dim: 1
  hidden_dim: 256
  num_layers: 8
  base_resolution: 64
  max_resolution: 1024
  activation_fn: Tanh
  coordinate_input_dim: 5
  dtype: float32

# --- 数据生成设置 ---
data_generation:
  num_samples: 2000                # 生成样本数量，可根据算力调整
  base_output_dir: data/processed  # 数据保存目录
  resolutions:                     # 支持多分辨率
    - [64, 64]
  domain_size_x: 10000.0
  domain_size_y: 10000.0
  parameter_type: scalar           # 标量参数
  parameter_ranges:                # 与 physics 区间保持一致
    uplift__rate: [0.0001, 0.002]
    spl__k_coef: [1.0e-6, 1.0e-4]
    diffusion__diffusivity: [0.01, 0.2]
    spl__area_exp: [0.4, 0.6]
    spl__slope_exp: [0.8, 1.2]
  initial_topo:
    mode: "waves"                  # 可选: waves, perlin, random_peaks
    amp_range: [10, 100]           # 波动幅值范围
    freq_range: [1, 8]             # 波动频率范围
    noise_std: 2                   # 叠加高斯噪声标准差
    smooth_sigma: 2                # 可选: 高斯平滑参数

# --- 物理参数 ---
physics:
  U_range: [0.0001, 0.002]
  K_f_range: [1.0e-6, 1.0e-4]
  K_d_range: [0.01, 0.2]
  m_range: [0.4, 0.6]
  n_range: [0.8, 1.2]
  precip_range: [0.5, 2.0]
  domain_x: [0.0, 10000.0]
  domain_y: [0.0, 10000.0]
  dx: ${eval:'(${physics.domain_x[1]} - ${physics.domain_x[0]}) / (${model.base_resolution} - 1)'}
  dy: ${eval:'(${physics.domain_y[1]} - ${physics.domain_y[0]}) / (${model.base_resolution} - 1)'}
  drainage_area_kwargs:
    initial_temp: 0.01
    end_temp: 1e-5
    annealing_factor: 0.98
    max_iters: 50
    lambda_dir: 1.0
    convergence_threshold: 1e-5
    special_depression_handling: true
    flat_handling: 'uniform'

# --- 训练设置 ---
training:
  max_epochs: 500
  batch_size: 64                # 4090显卡建议尝试64，如显存不足可适当调小
  optimizer: AdamW
  learning_rate: 2.0e-4         # 显卡性能提升可适当提高初始学习率
  weight_decay: 1.0e-5
  use_mixed_precision: true     # 强烈建议开启混合精度
  lr_scheduler: Cosine
  lr_scheduler_config:
    t_max: ${training.max_epochs}
    eta_min: 1e-7
  loss_weights:
    data: 1.0
    physics: 0.1
    smoothness: 0.001
  clip_grad_norm: 1.0
  val_interval: 1
  checkpoint_freq: 20           # 更频繁地保存检查点，防止长时间训练中断
  save_best_only: true

# --- 日志设置 ---
logging:
  log_level: INFO